language: java

git:
  depth: 1

before_install:
  - chmod +x gradlew

before_cache: # remove always changed files
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
  - rm -f  $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
  - rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
  - rm -f  $HOME/.gradle/caches/journal-1/journal-1.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - openjdk8
  - openjdk11
os:
  - linux
  # - windows (Not supported yet)
